import type { CaseCard } from "./types";
const rows = [
 ["demo-001","Valeria Montes Ríos",29,false,"missing","moderator_reviewed","priority","2026-08-08T18:20:00-05:00","Terminal Norte, Ciudad Ejemplo",4,"Fue reportada separada de su familia durante una evacuación."],
 ["demo-002","Mateo Salcedo Luna",11,true,"missing","moderator_reviewed","critical","2026-08-09T10:40:00-05:00","Zona aproximada del Refugio Central, Ciudad Ejemplo",2,"Fue visto por última vez mientras varias familias ingresaban al refugio."],
 ["demo-003","Ana Lucía Ferrer Gómez",63,false,"missing","moderator_reviewed","priority","2026-08-07T15:15:00-05:00","Mercado del Río, Ciudad Ejemplo",3,"Su familia perdió contacto con ella después del cierre de varias vías."],
 ["demo-004","Samuel Ortega Peña",37,false,"possibly_trapped","moderator_reviewed","critical","2026-08-10T07:30:00-05:00","Sector aproximado del Edificio Mirador, Ciudad Ejemplo",2,"Existen reportes revisados sobre el sector afectado."],
 ["demo-005","Camila Reyes Navarro",24,false,"located_alive","authority_confirmed","normal","2026-08-08T12:10:00-05:00","Centro de Atención Humanitaria, Ciudad Ejemplo",5,"Fue localizada con vida y trasladada a un centro de atención."],
 ["demo-006","Jorge Iván Molina Torres",52,false,"deceased_confirmed","authority_confirmed","normal","2026-08-06T19:00:00-05:00","Sector Occidental, Ciudad Ejemplo",1,"El fallecimiento fue confirmado dentro de estos datos ficticios de demostración."],
 ["demo-007","Sofía Cárdenas Gil",8,true,"reunited","authority_confirmed","normal","2026-08-09T09:25:00-05:00","Refugio Infantil, zona aproximada",3,"Fue localizada y reunida con su familia."],
 ["demo-008","Diego Andrés Pardo Vélez",41,false,"missing","unverified","priority","2026-08-10T21:05:00-05:00","Estación Sur, Ciudad Ejemplo",0,"Caso comunitario publicado con información aún no verificada."],
 ["demo-009","Rosa Elena Benítez Mora",70,false,"possibly_trapped","moderator_reviewed","critical","2026-08-10T06:45:00-05:00","Residencial Los Pinos, zona aproximada",1,"Existe información revisada sobre una edificación afectada."],
 ["demo-010","Nicolás Herrera Cruz",19,false,"missing","moderator_reviewed","priority","2026-08-08T23:10:00-05:00","Puente Central, Ciudad Ejemplo",6,"Varios reportes aprobados lo ubican cerca del puente."],
 ["demo-011","Mariana López Serrano",34,false,"missing","unverified","priority","2026-08-11T08:35:00-05:00","Ruta de Evacuación 4, Ciudad Ejemplo",1,"Su familia reportó la pérdida de contacto durante un traslado."],
 ["demo-012","Andrés Felipe Rincón Díaz",46,false,"located_alive","authority_confirmed","normal","2026-08-07T17:20:00-05:00","Puesto Médico Norte, Ciudad Ejemplo",2,"Fue localizado con vida y se confirmó su ingreso al puesto médico."],
 ["demo-013","Gabriela Suárez Nieto",27,false,"deceased_confirmed","authority_confirmed","normal","2026-08-06T14:50:00-05:00","Distrito Oriental, Ciudad Ejemplo",2,"El fallecimiento fue confirmado dentro de estos datos totalmente ficticios."],
 ["demo-014","Óscar Medina Quintero",58,false,"missing","moderator_reviewed","priority","2026-08-09T20:15:00-05:00","Parque Industrial, Ciudad Ejemplo",3,"Fue visto por última vez cerca de transporte comunitario."],
 ["demo-015","Luciana Torres Alba",15,true,"reunited","authority_confirmed","normal","2026-08-08T11:00:00-05:00","Centro Juvenil, zona aproximada",4,"Fue localizada con vida y reunida con su familia."]
] as const;
export const demoCases: CaseCard[] = rows.map(([id, full_name, approximate_age, is_minor, condition_status, verification_level, urgency_level, last_seen_at, last_seen_location_public, approved_reports_count, public_description]) => ({ id, slug: full_name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), full_name, approximate_age, is_minor, condition_status, verification_level, urgency_level, last_seen_at, last_seen_location_public, approved_reports_count, updated_at: last_seen_at, is_test_data: true, primary_public_photo_url: "/test-avatars/test-supplies.png", public_description }));
