export type ConditionStatus = "missing" | "possibly_trapped" | "located_alive" | "reunited" | "deceased_confirmed" | "closed";
export type VerificationLevel = "unverified" | "moderator_reviewed" | "authority_confirmed";
export type ReportType = "sighting" | "possible_trapped" | "possible_deceased" | "correction" | "other_information";
export type ReportContext = "sighting_alive" | "sighting_care";
export type CaseCard = {
  id: string;
  slug: string;
  full_name: string;
  approximate_age: number | null;
  is_minor: boolean;
  condition_status: ConditionStatus;
  verification_level: VerificationLevel;
  urgency_level: string;
  last_seen_at: string | null;
  last_seen_location_public: string | null;
  reported_unit?: string | null;
  primary_public_photo_url: string | null;
  approved_reports_count: number;
  updated_at: string;
  is_test_data: boolean;
  public_description?: string | null;
  public_source_label?: string | null;
  latest_approved_sighting_location?: string | null;
  approved_sightings_count?: number;
  approved_sightings?: Sighting[];
  sightings?: Sighting[];
};
export type Sighting = { id: string; event_at: string | null; location_public: string | null; description: string; reviewed_at?: string | null };

export type PendingCaseReport = {
  id: string;
  caseId: string;
  caseSlug: string;
  personName: string;
  reportType: ReportType;
  moderationStatus: "pending" | "escalated";
  urgencyLevel: string;
  eventAt: string | null;
  locationPrivate: string | null;
  descriptionPrivate: string;
  submittedAt: string;
  reporterName: string | null;
  phone: string | null;
  email: string | null;
  relationship: string | null;
  hasEvidence: boolean;
};
