-- Run only in local development or a dedicated demo project with ENABLE_TEST_DATA=true.
-- All people, locations and images are synthetic. The array values contain exactly 15 entries.
do $$ begin if coalesce(current_setting('app.enable_test_data', true),'false') <> 'true' then raise notice 'Skipping demo data; set app.enable_test_data=true for a demo environment.'; return; end if; end $$;
with data(test_key,full_name,age,is_minor,condition,verification,urgency,last_seen,location,description,report_count) as (values
('demo-001','Valeria Montes Ríos',29,false,'missing','moderator_reviewed','priority','2026-08-08T18:20:00-05:00','Terminal Norte, Ciudad Ejemplo','Fue reportada separada de su familia durante una evacuación.',4),
('demo-002','Mateo Salcedo Luna',11,true,'missing','moderator_reviewed','critical','2026-08-09T10:40:00-05:00','Zona aproximada del Refugio Central, Ciudad Ejemplo','Fue visto por última vez mientras varias familias ingresaban al refugio.',2),
('demo-003','Ana Lucía Ferrer Gómez',63,false,'missing','moderator_reviewed','priority','2026-08-07T15:15:00-05:00','Mercado del Río, Ciudad Ejemplo','Su familia perdió contacto con ella después del cierre de varias vías.',3),
('demo-004','Samuel Ortega Peña',37,false,'possibly_trapped','moderator_reviewed','critical','2026-08-10T07:30:00-05:00','Sector aproximado del Edificio Mirador, Ciudad Ejemplo','Existen reportes revisados sobre el sector afectado.',2),
('demo-005','Camila Reyes Navarro',24,false,'located_alive','authority_confirmed','normal','2026-08-08T12:10:00-05:00','Centro de Atención Humanitaria, Ciudad Ejemplo','Fue localizada con vida y trasladada a un centro de atención.',5),
('demo-006','Jorge Iván Molina Torres',52,false,'deceased_confirmed','authority_confirmed','normal','2026-08-06T19:00:00-05:00','Sector Occidental, Ciudad Ejemplo','El fallecimiento fue confirmado dentro de estos datos ficticios.',1),
('demo-007','Sofía Cárdenas Gil',8,true,'reunited','authority_confirmed','normal','2026-08-09T09:25:00-05:00','Refugio Infantil, zona aproximada','Fue localizada y reunida con su familia.',3),
('demo-008','Diego Andrés Pardo Vélez',41,false,'missing','unverified','priority','2026-08-10T21:05:00-05:00','Estación Sur, Ciudad Ejemplo','Caso comunitario publicado con información aún no verificada.',0),
('demo-009','Rosa Elena Benítez Mora',70,false,'possibly_trapped','moderator_reviewed','critical','2026-08-10T06:45:00-05:00','Residencial Los Pinos, zona aproximada','Existe información revisada sobre una edificación afectada.',1),
('demo-010','Nicolás Herrera Cruz',19,false,'missing','moderator_reviewed','priority','2026-08-08T23:10:00-05:00','Puente Central, Ciudad Ejemplo','Varios reportes aprobados lo ubican cerca del puente.',6),
('demo-011','Mariana López Serrano',34,false,'missing','unverified','priority','2026-08-11T08:35:00-05:00','Ruta de Evacuación 4, Ciudad Ejemplo','Su familia reportó la pérdida de contacto durante un traslado.',1),
('demo-012','Andrés Felipe Rincón Díaz',46,false,'located_alive','authority_confirmed','normal','2026-08-07T17:20:00-05:00','Puesto Médico Norte, Ciudad Ejemplo','Fue localizado con vida y se confirmó su ingreso al puesto médico.',2),
('demo-013','Gabriela Suárez Nieto',27,false,'deceased_confirmed','authority_confirmed','normal','2026-08-06T14:50:00-05:00','Distrito Oriental, Ciudad Ejemplo','El fallecimiento fue confirmado dentro de estos datos ficticios.',2),
('demo-014','Óscar Medina Quintero',58,false,'missing','moderator_reviewed','priority','2026-08-09T20:15:00-05:00','Parque Industrial, Ciudad Ejemplo','Fue visto por última vez cerca de transporte comunitario.',3),
('demo-015','Luciana Torres Alba',15,true,'reunited','authority_confirmed','normal','2026-08-08T11:00:00-05:00','Centro Juvenil, zona aproximada','Fue localizada con vida y reunida con su familia.',4))
, inserted_people as (insert into people(test_key,full_name,approximate_age,is_minor,public_description,is_test_data) select test_key,full_name,age,is_minor,description,true from data where coalesce(current_setting('app.enable_test_data', true),'false') = 'true' on conflict(test_key) do update set full_name=excluded.full_name returning id,test_key)
, inserted_cases as (insert into cases(person_id,slug,publication_status,condition_status,verification_level,urgency_level,last_seen_at,last_seen_location_public,circumstances_public,published_at,authority_reference_private,resolution_notes_private) select p.id, d.test_key||'-'||regexp_replace(public.normalize_person_name(d.full_name),' ','-','g'),'published',d.condition::condition_status,d.verification::verification_level,d.urgency::urgency_level,d.last_seen::timestamptz,d.location,d.description,now(),case when d.condition='deceased_confirmed' then 'Referencia ficticia de autoridad' else null end,case when d.condition='deceased_confirmed' then 'Confirmación ficticia para demo' else null end from data d join inserted_people p using(test_key) on conflict(person_id) do update set publication_status='published' returning id,person_id)
insert into case_reports(case_id,report_type,moderation_status,event_at,location_public,description) select c.id,'sighting','approved',d.last_seen::timestamptz,d.location,'Avistamiento ficticio aprobado para datos de demostración.' from inserted_cases c join people p on p.id=c.person_id join data d on d.test_key=p.test_key cross join lateral generate_series(1,d.report_count);
