"use client";
import { FormEvent, useState } from "react";

type Draft = Record<string, FormDataEntryValue>;
export default function ReportPage() {
  const [step, setStep] = useState(1), [draft, setDraft] = useState<Draft>({}), [done, setDone] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  function saveStep(form: HTMLFormElement) { setDraft((current) => ({ ...current, ...Object.fromEntries(new FormData(form)) })); }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; if (step < 3) { saveStep(form); return setStep(step + 1); } setBusy(true); setError(""); const body: Record<string, unknown> = { ...draft, ...Object.fromEntries(new FormData(form)) }; body.isMinor = draft.isMinor === "on"; body.consent = body.consent === "on"; body.goodFaith = body.goodFaith === "on"; const r = await fetch("/api/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await r.json(); setBusy(false); if (!r.ok) return setError(data.message); setDone(data.trackingCode); }
  if (done) return <section className="form-page"><div className="success" role="status"><h1>Reporte recibido</h1><p>Tu código de seguimiento es <strong>{done}</strong>.</p><p>El caso no se publica automáticamente. Un equipo revisará la información y podrá contactarte.</p></div></section>;
  return <section className="form-page"><h1>Reportar a una persona desaparecida</h1><p className="lead">Completa lo que sepas. Tu celular se mantiene privado.</p><p className="steps" aria-label={`Paso ${step} de 3`}>Paso {step} de 3</p><form className="report-form" onSubmit={submit}><input className="honeypot" aria-hidden="true" tabIndex={-1} name="website" autoComplete="off" />
    {step === 1 && <fieldset><legend>¿A quién buscas?</legend><label>Nombre completo<input name="fullName" required minLength={3} maxLength={140} defaultValue={String(draft.fullName || "")} /></label><label>Edad aproximada<input name="approximateAge" type="number" min="0" max="120" defaultValue={String(draft.approximateAge || "")} /></label></fieldset>}
    {step === 2 && <fieldset><legend>Última vez que fue vista</legend><label>Fecha<input name="lastSeenDate" type="date" required defaultValue={String(draft.lastSeenDate || "")} /></label><label>Hora aproximada<input name="lastSeenTime" type="time" defaultValue={String(draft.lastSeenTime || "")} /></label><label>Lugar aproximado<input name="location" required maxLength={240} defaultValue={String(draft.location || "")} /></label><label>Ropa que llevaba<textarea name="clothing" maxLength={800} defaultValue={String(draft.clothing || "")} /></label><label>Características distintivas<textarea name="features" maxLength={800} defaultValue={String(draft.features || "")} /></label></fieldset>}
    {step === 3 && <fieldset><legend>Celular y consentimiento</legend><label>Tu nombre (privado)<input name="reporterName" required defaultValue={String(draft.reporterName || "")} /></label><label>Número de celular (privado)<input name="phone" type="tel" inputMode="tel" required minLength={7} defaultValue={String(draft.phone || "")} /></label><p className="privacy-note">Usaremos este número solamente para revisar el reporte o pedir información adicional.</p><label className="check"><input name="consent" type="checkbox" required /> Autorizo procesar esta información para revisar el caso.</label><label className="check"><input name="goodFaith" type="checkbox" required /> Confirmo que la información se entrega de buena fe.</label></fieldset>}
    {error && <p role="alert" className="form-error">{error}</p>}<div className="form-actions">{step > 1 && <button type="button" className="button secondary" onClick={() => setStep(step - 1)}>Atrás</button>}<button className="button" disabled={busy}>{step === 3 ? (busy ? "Enviando…" : "Enviar reporte") : "Continuar"}</button></div></form></section>;
}
