-- Keep public reporting behind one narrowly scoped RPC. The function validates
-- its own input because anon callers can invoke it without the Next.js route.

alter table public.case_reports
  add column if not exists tracking_code text;

update public.case_reports
set tracking_code = 'EN-' || upper(replace(gen_random_uuid()::text, '-', ''))
where tracking_code is null;

alter table public.case_reports
  alter column tracking_code set default ('EN-' || upper(replace(gen_random_uuid()::text, '-', ''))),
  alter column tracking_code set not null;

create unique index if not exists case_reports_tracking_code_key
  on public.case_reports (tracking_code);

-- Persist only a keyed hash generated by the server, never an IP address.
-- This is intentionally database-backed so the limit survives server restarts
-- and applies across multiple Render instances.
create table if not exists public.submission_rate_limits (
  request_fingerprint text primary key check (request_fingerprint ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz not null default now(),
  submission_count integer not null default 0 check (submission_count >= 0),
  updated_at timestamptz not null default now()
);
alter table public.submission_rate_limits enable row level security;
revoke all on table public.submission_rate_limits from public, anon, authenticated, service_role;

-- Direct REST access is not a supported public data path. The narrowly scoped
-- RPCs below remain the only anonymous interface.
revoke all on public.public_case_cards from public, anon, authenticated;

-- The original split RPCs accepted unvalidated direct calls. Keep them only
-- for trusted database operators; public clients use submit_public_report.
revoke all on function public.submit_missing_person_report(text,text,int,boolean,timestamptz,text,text,text,text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.submit_public_information(uuid,public.report_type,timestamptz,text,text) from public, anon, authenticated;

create or replace function public.submit_public_report(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_kind text;
  v_case_reference text;
  v_case_id uuid;
  v_report_type_text text;
  v_report_type public.report_type;
  v_event_at timestamptz;
  v_location text;
  v_description text;
  v_full_name text;
  v_normalized_name text;
  v_alias text;
  v_age_text text;
  v_age integer;
  v_is_minor boolean;
  v_last_seen_at timestamptz;
  v_clothing text;
  v_features text;
  v_circumstances text;
  v_reporter_name text;
  v_phone text;
  v_email text;
  v_preferred_contact text;
  v_person_id uuid;
  v_report_id uuid;
  v_tracking_code text;
  v_request_fingerprint text;
  v_submission_count integer;
  v_now timestamptz := clock_timestamp();
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'Invalid report payload';
  end if;

  v_request_fingerprint := nullif(btrim(p_payload ->> 'requestFingerprint'), '');
  if v_request_fingerprint is null or v_request_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'Invalid submission fingerprint';
  end if;

  insert into public.submission_rate_limits as limits (
    request_fingerprint,
    window_started_at,
    submission_count,
    updated_at
  ) values (
    v_request_fingerprint,
    v_now,
    1,
    v_now
  ) on conflict (request_fingerprint) do update set
    window_started_at = case
      when limits.window_started_at <= v_now - interval '15 minutes' then v_now
      else limits.window_started_at
    end,
    submission_count = case
      when limits.window_started_at <= v_now - interval '15 minutes' then 1
      else limits.submission_count + 1
    end,
    updated_at = v_now
  returning submission_count into v_submission_count;

  if v_submission_count > 5 then
    raise exception using errcode = 'P0001', message = 'Submission rate limit reached';
  end if;

  v_kind := nullif(btrim(p_payload ->> 'kind'), '');
  if v_kind is null or v_kind not in ('missing_person', 'case_information') then
    raise exception using errcode = '22023', message = 'Invalid report kind';
  end if;

  if v_kind = 'case_information' then
    v_case_reference := nullif(btrim(p_payload ->> 'caseId'), '');
    if v_case_reference is null then
      raise exception using errcode = '22023', message = 'A case reference is required';
    end if;

    if v_case_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
      select c.id
      into v_case_id
      from public.cases c
      where c.id = v_case_reference::uuid
        and c.publication_status = 'published'
        and c.deleted_at is null
      for key share;
    else
      raise exception using errcode = '22023', message = 'Invalid case reference';
    end if;

    if v_case_id is null then
      raise exception using errcode = 'P0002', message = 'Case is not available for public reports';
    end if;

    v_report_type_text := nullif(btrim(p_payload ->> 'reportType'), '');
    if v_report_type_text is null or v_report_type_text not in ('sighting', 'possible_trapped', 'possible_deceased', 'correction', 'other_information') then
      raise exception using errcode = '22023', message = 'Invalid report type';
    end if;
    v_report_type := v_report_type_text::public.report_type;

    v_location := nullif(btrim(p_payload ->> 'location'), '');
    if v_location is not null and char_length(v_location) > 240 then
      raise exception using errcode = '22023', message = 'Location is too long';
    end if;

    v_description := nullif(btrim(p_payload ->> 'description'), '');
    if v_description is null or char_length(v_description) < 10 or char_length(v_description) > 3000 then
      raise exception using errcode = '22023', message = 'Description must be between 10 and 3000 characters';
    end if;

    if nullif(btrim(p_payload ->> 'eventAt'), '') is not null then
      begin
        v_event_at := (p_payload ->> 'eventAt')::timestamptz;
      exception when others then
        raise exception using errcode = '22023', message = 'Invalid event timestamp';
      end;
    end if;

    insert into public.case_reports (
      case_id,
      report_type,
      event_at,
      location_private,
      location_public,
      description,
      urgency_level,
      is_sensitive
    ) values (
      v_case_id,
      v_report_type,
      v_event_at,
      v_location,
      null,
      v_description,
      case when v_report_type = 'possible_trapped' then 'urgent' else 'normal' end,
      true
    ) returning id, tracking_code into v_report_id, v_tracking_code;

    return jsonb_build_object('tracking_code', v_tracking_code);
  end if;

  v_full_name := nullif(btrim(p_payload ->> 'fullName'), '');
  if v_full_name is null or char_length(v_full_name) < 3 or char_length(v_full_name) > 140 then
    raise exception using errcode = '22023', message = 'Full name must be between 3 and 140 characters';
  end if;

  v_normalized_name := public.normalize_person_name(v_full_name);
  if v_normalized_name = '' then
    raise exception using errcode = '22023', message = 'Full name cannot be normalized';
  end if;

  v_alias := nullif(btrim(p_payload ->> 'alias'), '');
  if v_alias is not null and char_length(v_alias) > 140 then
    raise exception using errcode = '22023', message = 'Alias is too long';
  end if;

  v_age_text := nullif(btrim(p_payload ->> 'approximateAge'), '');
  if v_age_text is not null then
    if v_age_text !~ '^[0-9]{1,3}$' then
      raise exception using errcode = '22023', message = 'Invalid approximate age';
    end if;
    v_age := v_age_text::integer;
    if v_age > 120 then
      raise exception using errcode = '22023', message = 'Invalid approximate age';
    end if;
  end if;

  if jsonb_typeof(p_payload -> 'isMinor') <> 'boolean' then
    raise exception using errcode = '22023', message = 'isMinor must be a boolean';
  end if;
  v_is_minor := (p_payload ->> 'isMinor')::boolean;

  if nullif(btrim(p_payload ->> 'lastSeenAt'), '') is null then
    raise exception using errcode = '22023', message = 'Last seen timestamp is required';
  end if;
  begin
    v_last_seen_at := (p_payload ->> 'lastSeenAt')::timestamptz;
  exception when others then
    raise exception using errcode = '22023', message = 'Invalid last seen timestamp';
  end;

  v_location := nullif(btrim(p_payload ->> 'location'), '');
  if v_location is null or char_length(v_location) < 3 or char_length(v_location) > 240 then
    raise exception using errcode = '22023', message = 'Location must be between 3 and 240 characters';
  end if;

  v_clothing := nullif(btrim(p_payload ->> 'clothing'), '');
  v_features := nullif(btrim(p_payload ->> 'features'), '');
  v_circumstances := nullif(btrim(p_payload ->> 'circumstances'), '');
  if (v_clothing is not null and char_length(v_clothing) > 800)
    or (v_features is not null and char_length(v_features) > 800)
    or (v_circumstances is not null and char_length(v_circumstances) > 3000) then
    raise exception using errcode = '22023', message = 'Report detail is too long';
  end if;

  v_reporter_name := nullif(btrim(p_payload ->> 'reporterName'), '');
  if v_reporter_name is null or char_length(v_reporter_name) < 2 or char_length(v_reporter_name) > 140 then
    raise exception using errcode = '22023', message = 'Reporter name must be between 2 and 140 characters';
  end if;

  v_phone := nullif(btrim(p_payload ->> 'phone'), '');
  if v_phone is not null and (char_length(v_phone) < 7 or char_length(v_phone) > 40 or v_phone !~ '^[0-9+ ()-]+$') then
    raise exception using errcode = '22023', message = 'Invalid phone number';
  end if;

  v_email := nullif(btrim(p_payload ->> 'email'), '');
  if v_email is not null and (char_length(v_email) > 254 or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$') then
    raise exception using errcode = '22023', message = 'Invalid email address';
  end if;
  if v_phone is null and v_email is null then
    raise exception using errcode = '22023', message = 'A contact method is required';
  end if;

  v_preferred_contact := nullif(btrim(p_payload ->> 'preferredContact'), '');
  if v_preferred_contact is not null and char_length(v_preferred_contact) > 40 then
    raise exception using errcode = '22023', message = 'Preferred contact method is too long';
  end if;

  insert into public.people (
    full_name,
    aliases,
    approximate_age,
    is_minor,
    distinguishing_features,
    private_notes
  ) values (
    v_full_name,
    case when v_alias is null then '{}'::text[] else array[v_alias] end,
    v_age,
    v_is_minor,
    v_features,
    v_circumstances
  ) returning id into v_person_id;

  insert into public.cases (
    person_id,
    slug,
    publication_status,
    condition_status,
    last_seen_at,
    last_seen_location_public,
    last_seen_location_private,
    clothing,
    circumstances_public,
    circumstances_private,
    urgency_level
  ) values (
    v_person_id,
    v_normalized_name || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 12),
    'pending_review',
    'missing',
    v_last_seen_at,
    null,
    v_location,
    v_clothing,
    null,
    v_circumstances,
    case when v_is_minor then 'priority' else 'normal' end
  ) returning id into v_case_id;

  insert into public.case_reports (
    case_id,
    report_type,
    description,
    is_sensitive
  ) values (
    v_case_id,
    'other_information',
    'Initial family report',
    true
  ) returning id, tracking_code into v_report_id, v_tracking_code;

  insert into public.reporter_contacts (
    report_id,
    reporter_name,
    phone,
    email,
    preferred_contact_method
  ) values (
    v_report_id,
    v_reporter_name,
    v_phone,
    v_email,
    v_preferred_contact
  );

  return jsonb_build_object('tracking_code', v_tracking_code);
end;
$$;

revoke all on function public.submit_public_report(jsonb) from public;
revoke all on function public.submit_public_report(jsonb) from anon, authenticated;
grant execute on function public.submit_public_report(jsonb) to service_role;

-- The dedicated demo seeder authenticates as service_role. These grants do
-- not apply to public clients and RLS remains enabled for normal roles.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.people, public.cases, public.case_reports, public.media_assets to service_role;

-- Public death confirmation requires meaningful authority and reason values,
-- not merely non-NULL placeholders. NOT VALID protects future writes without
-- blocking deployment until any historical records can be reviewed.
alter table public.cases
  add constraint cases_deceased_confirmation_details_check
  check (
    condition_status <> 'deceased_confirmed'
    or (
      verification_level = 'authority_confirmed'
      and nullif(btrim(authority_reference_private), '') is not null
      and nullif(btrim(resolution_notes_private), '') is not null
    )
  ) not valid;

-- Resolve a fictional card reference only through this read RPC. The route
-- below permits that reference solely when its own demo environment is on;
-- submit_public_report itself accepts UUIDs only.
create or replace function public.get_public_case(case_slug text)
returns setof public.public_case_cards
language sql
stable
security definer
set search_path = pg_catalog, public, pg_temp
as $$
  select v.*
  from public.public_case_cards v
  join public.cases c on c.id = v.id
  join public.people p on p.id = c.person_id
  where v.slug = case_slug
     or (p.is_test_data and p.test_key = case_slug)
$$;

-- Status updates already require staff RLS. Executing this trigger as its
-- owner lets the required history and audit inserts succeed without granting
-- staff arbitrary access to audit_logs.
create or replace function public.case_safety_trigger()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if new.condition_status = 'deceased_confirmed' and (
    new.verification_level <> 'authority_confirmed'
    or nullif(btrim(new.authority_reference_private), '') is null
    or nullif(btrim(new.resolution_notes_private), '') is null
    or (
      not public.is_admin()
      and not (
        coalesce(current_setting('app.enable_test_data', true), 'false') = 'true'
        and exists (select 1 from public.people where id = new.person_id and is_test_data)
      )
    )
  ) then
    raise exception 'Only an admin can confirm a death with authority reference and reason';
  end if;

  if tg_op = 'INSERT' and new.condition_status = 'deceased_confirmed' then
    if auth.uid() is null then
      raise exception 'An actor is required';
    end if;

    insert into public.status_history (
      case_id,
      previous_condition,
      new_condition,
      previous_verification,
      new_verification,
      reason,
      authority_reference_private,
      actor_id
    ) values (
      new.id,
      null,
      new.condition_status,
      null,
      new.verification_level,
      new.resolution_notes_private,
      new.authority_reference_private,
      auth.uid()
    );

    insert into public.audit_logs (actor_id, action, entity_type, entity_id)
    values (auth.uid(), 'case_deceased_confirmed_created', 'case', new.id);
  elsif tg_op = 'UPDATE' and new.condition_status is distinct from old.condition_status then
    if auth.uid() is null then
      raise exception 'An actor is required';
    end if;

    insert into public.status_history (
      case_id,
      previous_condition,
      new_condition,
      previous_verification,
      new_verification,
      reason,
      authority_reference_private,
      actor_id
    ) values (
      new.id,
      old.condition_status,
      new.condition_status,
      old.verification_level,
      new.verification_level,
      coalesce(new.resolution_notes_private, 'Status update'),
      new.authority_reference_private,
      auth.uid()
    );

    insert into public.audit_logs (actor_id, action, entity_type, entity_id)
    values (auth.uid(), 'case_status_changed', 'case', new.id);
  end if;

  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.case_safety_trigger() from public;
