-- Encontrarnos: private-by-default humanitarian data model.
create extension if not exists pg_trgm;
create extension if not exists unaccent;
create extension if not exists pgcrypto;

create type public.publication_status as enum ('draft','pending_review','published','hidden','archived');
create type public.condition_status as enum ('missing','possibly_trapped','located_alive','reunited','deceased_confirmed','closed');
create type public.verification_level as enum ('unverified','moderator_reviewed','authority_confirmed');
create type public.report_type as enum ('sighting','possible_trapped','possible_deceased','correction','other_information');
create type public.moderation_status as enum ('pending','approved','rejected','duplicate','escalated');
create type public.urgency_level as enum ('normal','priority','urgent','critical');
create type public.app_role as enum ('public','reporter','moderator','responder','admin');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, role app_role not null default 'public', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.people (id uuid primary key default gen_random_uuid(), test_key text unique, full_name text not null check (char_length(full_name) between 3 and 140), normalized_name text not null, aliases text[] not null default '{}', approximate_age smallint check (approximate_age between 0 and 120), birth_date date, is_minor boolean not null default false, gender text, distinguishing_features text, public_description text, private_notes text, is_test_data boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cases (id uuid primary key default gen_random_uuid(), person_id uuid not null unique references public.people(id), slug text not null unique, publication_status publication_status not null default 'pending_review', condition_status condition_status not null default 'missing', verification_level verification_level not null default 'unverified', urgency_level urgency_level not null default 'normal', last_seen_at timestamptz, last_seen_location_public text, last_seen_location_private text, latitude_private numeric, longitude_private numeric, latitude_public_approx numeric, longitude_public_approx numeric, clothing text, circumstances_public text, circumstances_private text, primary_public_photo_path text, created_by uuid references auth.users(id), reviewed_by uuid references auth.users(id), authority_reference_private text, resolution_notes_private text, published_at timestamptz, resolved_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (condition_status <> 'deceased_confirmed' or (verification_level = 'authority_confirmed' and authority_reference_private is not null and resolution_notes_private is not null)), check (not (publication_status = 'published' and deleted_at is not null)));
create table public.case_reports (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id), report_type report_type not null, moderation_status moderation_status not null default 'pending', urgency_level urgency_level not null default 'normal', reporter_user_id uuid references auth.users(id), event_at timestamptz, location_public text, location_private text, latitude_private numeric, longitude_private numeric, description text not null check (char_length(description) between 10 and 3000), confidence_self_reported text, is_sensitive boolean not null default false, deduplication_hash text, submitted_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references auth.users(id), rejection_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reporter_contacts (id uuid primary key default gen_random_uuid(), report_id uuid not null unique references public.case_reports(id) on delete cascade, reporter_name text not null, relationship_to_person text, phone text, email text, preferred_contact_method text, consent_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.media_assets (id uuid primary key default gen_random_uuid(), case_id uuid references public.cases(id), report_id uuid references public.case_reports(id), asset_type text not null check(asset_type in ('portrait','evidence','attachment')), storage_bucket text not null, private_path text not null, public_path text, original_filename text, detected_mime_type text, size_bytes integer, created_at timestamptz not null default now());
create table public.status_history (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id), previous_condition condition_status, new_condition condition_status not null, previous_verification verification_level, new_verification verification_level not null, reason text not null, authority_reference_private text, actor_id uuid references auth.users(id), created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create function public.normalize_person_name(value text) returns text language sql immutable as $$ select trim(regexp_replace(lower(unaccent(coalesce(value,''))), '[^a-z0-9ñ]+', ' ', 'g')) $$;
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and active and role in ('moderator','responder','admin')) $$;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and active and role='admin') $$;
create function public.people_normalize_trigger() returns trigger language plpgsql as $$ begin new.normalized_name := public.normalize_person_name(new.full_name); new.updated_at:=now(); return new; end $$;
create trigger people_normalize before insert or update of full_name on public.people for each row execute function public.people_normalize_trigger();
create function public.case_safety_trigger() returns trigger language plpgsql as $$ begin if new.condition_status='deceased_confirmed' and (new.verification_level <> 'authority_confirmed' or new.authority_reference_private is null or new.resolution_notes_private is null or (not public.is_admin() and not (coalesce(current_setting('app.enable_test_data',true),'false')='true' and exists(select 1 from public.people where id=new.person_id and is_test_data)))) then raise exception 'Only an admin can confirm a death with authority reference and reason'; end if; if tg_op='UPDATE' and new.condition_status is distinct from old.condition_status then if auth.uid() is null then raise exception 'An actor is required'; end if; insert into public.status_history(case_id,previous_condition,new_condition,previous_verification,new_verification,reason,authority_reference_private,actor_id) values(new.id,old.condition_status,new.condition_status,old.verification_level,new.verification_level,coalesce(new.resolution_notes_private,'Status update'),new.authority_reference_private,auth.uid()); insert into public.audit_logs(actor_id,action,entity_type,entity_id) values(auth.uid(),'case_status_changed','case',new.id); end if; new.updated_at:=now(); return new; end $$;
create trigger cases_safety before insert or update on public.cases for each row execute function public.case_safety_trigger();

create view public.public_case_cards with (security_invoker=false) as select c.id,c.slug,p.full_name,p.approximate_age,p.is_minor,c.condition_status,c.verification_level,c.urgency_level,c.last_seen_at,c.last_seen_location_public,ma.public_path as primary_public_photo_url,(select count(*) from public.case_reports r where r.case_id=c.id and r.moderation_status='approved' and r.report_type='sighting')::int as approved_reports_count,c.updated_at,p.is_test_data,p.public_description,p.distinguishing_features,c.clothing from public.cases c join public.people p on p.id=c.person_id left join lateral (select public_path from public.media_assets where case_id=c.id and asset_type='portrait' and public_path is not null limit 1) ma on true where c.publication_status='published' and c.deleted_at is null;

create function public.search_public_people(query_text text default '', status_filter text default null, min_age int default null, max_age int default null, page_limit int default 24, page_offset int default 0) returns setof public.public_case_cards language sql stable security definer set search_path=public as $$ select * from public.public_case_cards v where (status_filter is null or v.condition_status::text=status_filter) and (min_age is null or v.approximate_age>=min_age) and (max_age is null or v.approximate_age<=max_age) and (query_text='' or public.normalize_person_name(v.full_name) % public.normalize_person_name(query_text) or public.normalize_person_name(v.full_name) like public.normalize_person_name(query_text)||'%' or coalesce(v.last_seen_location_public,'') ilike '%'||query_text||'%' or coalesce(v.public_description,'') ilike '%'||query_text||'%') order by similarity(public.normalize_person_name(v.full_name),public.normalize_person_name(query_text)) desc, v.updated_at desc limit least(greatest(page_limit,1),48) offset greatest(page_offset,0) $$;
create function public.get_public_case(case_slug text) returns setof public.public_case_cards language sql stable security definer set search_path=public as $$ select * from public.public_case_cards where slug=case_slug $$;
create function public.submit_missing_person_report(p_full_name text,p_alias text,p_age int,p_is_minor boolean,p_last_seen_at timestamptz,p_location text,p_clothing text,p_features text,p_circumstances text,p_reporter_name text,p_phone text,p_email text,p_preferred_contact text) returns jsonb language plpgsql security definer set search_path=public as $$ declare pid uuid; cid uuid; rid uuid; code text; begin if p_phone is null and p_email is null then raise exception 'contact required'; end if; insert into people(full_name,aliases,approximate_age,is_minor,distinguishing_features,public_description) values(p_full_name,case when p_alias is null then '{}' else array[p_alias] end,p_age,p_is_minor,p_features,p_circumstances) returning id into pid; insert into cases(person_id,slug,publication_status,condition_status,last_seen_at,last_seen_location_public,last_seen_location_private,clothing,circumstances_public,urgency_level) values(pid,public.normalize_person_name(p_full_name)||'-'||substr(replace(gen_random_uuid()::text,'-',''),1,8),'pending_review','missing',p_last_seen_at,case when p_is_minor then 'Zona aproximada: '||left(p_location,80) else p_location end,p_location,p_clothing,p_circumstances,case when p_is_minor then 'priority' else 'normal' end) returning id into cid; insert into case_reports(case_id,report_type,description) values(cid,'other_information','Initial family report') returning id into rid; insert into reporter_contacts(report_id,reporter_name,phone,email,preferred_contact_method) values(rid,p_reporter_name,p_phone,p_email,p_preferred_contact); code:='EN-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)); return jsonb_build_object('tracking_code',code); end $$;
create function public.submit_public_information(p_case_id uuid,p_type report_type,p_event_at timestamptz,p_location text,p_description text) returns jsonb language plpgsql security definer set search_path=public as $$ declare code text; begin insert into case_reports(case_id,report_type,event_at,location_private,location_public,description,urgency_level,is_sensitive) values(p_case_id,p_type,p_event_at,p_location,case when p_type in ('possible_trapped','possible_deceased') then null else p_location end,p_description,case when p_type='possible_trapped' then 'urgent' else 'normal' end,p_type in ('possible_trapped','possible_deceased')); code:='EN-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)); return jsonb_build_object('tracking_code',code); end $$;

alter table public.profiles enable row level security; alter table public.people enable row level security; alter table public.cases enable row level security; alter table public.case_reports enable row level security; alter table public.reporter_contacts enable row level security; alter table public.media_assets enable row level security; alter table public.status_history enable row level security; alter table public.audit_logs enable row level security;
create policy "staff only profiles" on public.profiles for all using (id=auth.uid() or public.is_admin()) with check (public.is_admin());
create policy "staff only people" on public.people for all using (public.is_staff()) with check (public.is_staff()); create policy "staff only cases" on public.cases for all using (public.is_staff()) with check (public.is_staff()); create policy "staff only reports" on public.case_reports for all using (public.is_staff()) with check (public.is_staff()); create policy "staff contacts" on public.reporter_contacts for all using (public.is_staff()) with check (public.is_staff()); create policy "staff media" on public.media_assets for all using (public.is_staff()) with check (public.is_staff()); create policy "staff history" on public.status_history for all using (public.is_staff()) with check (public.is_staff()); create policy "admin audit" on public.audit_logs for select using (public.is_admin());
grant execute on function public.search_public_people(text,text,int,int,int,int), public.get_public_case(text), public.submit_missing_person_report(text,text,int,boolean,timestamptz,text,text,text,text,text,text,text,text), public.submit_public_information(uuid,report_type,timestamptz,text,text) to anon, authenticated;
revoke all on public.reporter_contacts,public.audit_logs,public.status_history from anon,authenticated;
